name: Build and Validate

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend
        run: docker build -t stackops-backend ./backend

      - name: Build frontend
        run: docker build -t stackops-frontend ./frontend
